### PR TITLE
Update for use with Elm 0.13

### PR DESCRIPTION
**Pull request by gergoerdi**

### CODE REVIEW

**Comment by jcollard** [comment]
Cool. Thanks!

**Comment by gergoerdi** [comment]
I think you accidentally haven't actually merged my changes.

**Comment by jcollard** [comment]
Not sure how that happened. very strange. Thanks again.

**Comment by gergoerdi** [comment]
Now that `elm-audio` works with Elm 0.13, do you have plans to add it to the global Elm package repository at http://package.elm-lang.org/packages ?

**Comment by jcollard** [comment]
One of my main reasons for not doing this is that it has a Native module which needs to go through an approval process. Unfortunately, at this time I don't think I would have time to go through any revisions that might be required. Would you be interested in being a collaborator on this project?

Also, do you mean Elm 0.14?

**Comment by gergoerdi** [comment]
Yeah, I meant Elm 0.14.

Didn't know about the Native restriction, that's a bummer I guess. TBH I only plan to use the whole of Elm for single project that I will only be able to reveal in a week and then promptly abandon,

The fact that there's a Ludum Dare mini-challenge next week is not a coincidence ;)

**Pull request merged**
